# Generated by Django 3.0.8 on 2020-10-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradstud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acadinfo',
            name='firstname',
            field=models.CharField(default='name', max_length=64),
        ),
        migrations.AddField(
            model_name='acadinfo',
            name='lastname',
            field=models.CharField(default='surname', max_length=64),
        ),
        migrations.AlterField(
            model_name='acadinfo',
            name='gpa',
            field=models.FloatField(default=4),
        ),
        migrations.AlterField(
            model_name='acadinfo',
            name='greawa',
            field=models.FloatField(default=4),
        ),
        migrations.AlterField(
            model_name='acadinfo',
            name='greq',
            field=models.IntegerField(default=170),
        ),
        migrations.AlterField(
            model_name='acadinfo',
            name='grev',
            field=models.IntegerField(default=170),
        ),
        migrations.AlterField(
            model_name='acadinfo',
            name='lor1',
            field=models.EmailField(default='chinmayagrawal90@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='acadinfo',
            name='lor2',
            field=models.EmailField(default='chinmayagrawal90@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='acadinfo',
            name='lor3',
            field=models.EmailField(default='chinmayagrawal90@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='acadinfo',
            name='pubven',
            field=models.CharField(default='ICML', max_length=64),
        ),
        migrations.AlterField(
            model_name='acadinfo',
            name='rmonths',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='acadinfo',
            name='ugmajor',
            field=models.CharField(default='major', max_length=64),
        ),
        migrations.AlterField(
            model_name='acadinfo',
            name='university',
            field=models.CharField(default='uni', max_length=64),
        ),
        migrations.AlterField(
            model_name='acadinfo',
            name='wmonths',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='acadinfo',
            name='wtype',
            field=models.CharField(default='FAANG', max_length=64),
        ),
    ]
