# Generated by Django 3.0.8 on 2020-10-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradstud', '0002_auto_20201011_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acadinfo',
            name='gpa',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='acadinfo',
            name='greawa',
            field=models.IntegerField(default=4),
        ),
    ]
