# Generated by Django 3.0.8 on 2020-10-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradstud', '0004_auto_20201011_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='acadinfo',
            name='lor1n',
            field=models.CharField(default='Chinmay Agrawal', max_length=100),
        ),
        migrations.AddField(
            model_name='acadinfo',
            name='lor2n',
            field=models.CharField(default='Chinmay Agrawal', max_length=100),
        ),
        migrations.AddField(
            model_name='acadinfo',
            name='lor3n',
            field=models.CharField(default='Chinmay Agrawal', max_length=100),
        ),
        migrations.AddField(
            model_name='acadinfo',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
